# Generated by Django 5.0.3 on 2024-03-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
                ('seats_taken', models.IntegerField(blank=True, null=True)),
                ('qr_token', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_qr_login', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
