# Generated by Django 5.0.3 on 2024-03-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='is_qr_login',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='username',
            field=models.CharField(max_length=602),
        ),
    ]
