# Generated by Django 5.0.3 on 2024-05-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='is_closed'),
        ),
    ]
